global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@foliofox.local'
  smtp_auth_username: ''
  smtp_auth_password: ''

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://webhook-url/alerts'
        send_resolved: true
    
  - name: 'email'
    email_configs:
      - to: 'admin@foliofox.local'
        subject: 'FolioFox Alert: {{ .GroupLabels.alertname }}'
        body: |
          Alert Details:
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Instance: {{ .Labels.instance }}
          
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']